"""'t1'

Revision ID: 42de65121120
Revises: d84be1cf086e
Create Date: 2020-03-18 13:46:39.143274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42de65121120'
down_revision = 'd84be1cf086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liked_user_id', sa.Integer(), nullable=True),
    sa.Column('liked_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['liked_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_post')
    # ### end Alembic commands ###
