"""'t4'

Revision ID: dfcbda7ddf3b
Revises: 42de65121120
Create Date: 2020-03-21 18:09:34.661472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcbda7ddf3b'
down_revision = '42de65121120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_picture', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_picture')
    # ### end Alembic commands ###
